package enis.gui.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PodvozekFormDesign extends FormLayout {
    protected TextField vzdalOtocCepuPodvozkuTF;
    protected TextField rozvorPodvozkuTF;
    protected TextField unosnostKonstrukcniTF;
    protected TextField pocetPodvozuTF;
    protected TextField pocetClankuTF;
    protected TextField pocetNapravTF;

    public PodvozekFormDesign() {
		Design.read(this);
	}
}
